name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build -- --configuration production
    - name: Run tests
      run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
    - name: Generate code coverage report
      run: npm run test -- --code-coverage
    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage/
